### ISSUE TITLE
Add function to configure the quality of the Encoder

### ISSUE THREAD

**Issue by SeaDve** [image-rs/image-gif#107]
This would help restricting the CPU usage, as sometimes, it can get buggy when the CPU is trying to catch up while encoding gif.

**Comment by fintelia** [comment]
Have you looked at [Frame::from_rgb_speed](https://docs.rs/gif/0.11.2/gif/struct.Frame.html#method.from_rgb_speed)? That may do what you are looking for

**Comment by SeaDve** [comment]
thanks!

**Comment by SeaDve** [comment]
I realize that it doesn't reduce the file size that much,

**Comment by fintelia** [comment]
That setting should impact the encoding speed and the resulting image quality, but not the file size. GIF is a pretty old format, so it might not actually be possible to get files as small as you'd like. Have you found other software that can produce substantially smaller GIFs?

**Comment by SeaDve** [comment]
Ffmpeg's default settings produce a lot lower quality gif, but the size is also substantially smaller.

**Comment by fintelia** [comment]
Could you create a new issue (the topic's somewhat drifting on this one) with a source image and the resulting output from ffmpeg and image-gif? That would be a good starting point for someone to investigate how ffmpeg produces substantially smaller images than we do

**Comment by SeaDve** [comment]
okay, should i close this?
