### ISSUE TITLE
NeuQuant seems inappropriate for limited-colour images

### ISSUE THREAD

**Issue by simon-frankau** [image-rs/image-gif#109]
Hi.

This is a kind of upstream investigation of https://github.com/38/plotters/issues/273.

It looks like this library always uses NeuQuant to generate palettes, even if the source image has a limited number of colours and could just be converted directly into a paletted image. This is both slower than necessary, and can produce surprisingly sub-optimal palettes (see above bug).

I guess the normal response is "Use `from_palette_pixels` or `from_indexed_pixels` for limited-colour images, however people accessing the gif crate through the image crate (https://github.com/image-rs/image/blob/master/README.md) don't seem to have the option to provide an explicit palette.

My knowledge of image-gif and image are very limited, but I think I can see two main options to providing a convenient interface:

 * image-gif recognises images with < 256 colours and generates palettes directly without NeuQuant.
 * image, when calling to image-gif, recognises images with < 256 colours, and does the conversion to a palette-based call.

I think the first option is more general, is likely to have minimal performance impact in the high-colour case, and improve both performance and output quality in the low-colour case.

My Rust is somewhat basic, but I would be happy to try to contribute a PR if this solution sounds acceptable.

Thanks,
Simon.

**Comment by fintelia** [comment]
This all sounds reasonable. I'd welcome a PR for image-gif to recognize whether there's already < 256 colors before calling into NeuQuant

**Comment by simon-frankau** [comment]
Thanks. I'm making a start on it, but my free time is a little unpredictable at the moment. I think I'll also appreciate code review on my style, as my knowledge of idiomatic rust (let alone the specific style for image-gif!) is pretty limited, but I guess we can deal with that once I've got a rough draft.

**Comment by simon-frankau** [comment]
I've raised https://github.com/image-rs/image-gif/pull/110 for this issue.

**Comment by simon-frankau** [comment]
Hi. Is there anything I can do to help move this along? I've updated the PR after code review, but I don't know if there's anything else I should be doing. Cheers.
