### ISSUE TITLE
Implement Iterator on Decoder

### ISSUE THREAD

**Issue by tobiasvl** [image-rs/image-gif#134]
I'm a Rust newbie, so I might be thinking weirdly here, but the current structure where `Decoder` is a struct that holds global information about the GIF (color and palette) and also state information (current frame) seems very strange to me.

Wouldn't it be more idiomatic if there was a struct with the global information, which you could then get an iterator from that would iterate over the frames?

I was just trying to use the global palette as a fallback for frames that lack frame palettes:
```rust
while let Ok(Some(frame)) = decoder.read_next_frame() { // mutable borrow
    let palette = frame
        .palette
        .as_ref()
        .and_then(|p| Some(&p[..])) // frame.palette is Vec<u8>, global_palette is &[u8]
        .unwrap_or(decoder.global_palette().ok_or(Error::PaletteError)?); // immutable borrow
    // ...
}
```
which obviously doesn't work since `decoder` is borrowed mutably for the loop. There might be better ways to do this (although cloning the global palette before the loop doesn't feel like it's better), but it just feels strange to me that iterating over frames need a mutable borrow of the entire `Decoder`, and it feels like this should be an `Iterator`.

**Comment by HeroicKatora** [comment]
Items yielded by an iterator must be `'static` and can't borrow from the decoder. Hence we would have to clone or reference count all shared information if it were to implement `Iterator`. It's not possible without some form of other overhead.
