### ISSUE TITLE
Delay not working when set to 1 or 0

### ISSUE THREAD

**Issue by IsotoxalDev** [image-rs/image-gif#137]
i am converting an animation of 100FPS into GIF but when the delay is set to 1 ie 10 ms. it generates a 10FPS gif

**Comment by HeroicKatora** [comment]
That's [standard behavior](https://www.biphelps.com/blog/The-Fastest-GIF-Does-Not-Exist?source=techstories.org) caused by the displaying program. Not on us to decide, don't use gif for anything where you need precise control. Prefer webp, for instance.
