### ISSUE TITLE
Gif decoding hangs forever if invalid frame is encountered

### ISSUE THREAD

**Issue by woelper** [image-rs/image-gif#145]
This happens in image `0.24.4`.

I am trying to load valid frames of a Gif which contains unknown block types. I am aware this is not a valid image, but I would load all frames which decode ok. For this, I am simply calling `into_frames()` of the decoder and testing if each one is Ok. However the iterator hangs once an invalid frame is encountered and pauses execution. 

## Expected
iterating frames should complete regardless of decoding success

What behaviour should have happened
the iterator should finish

## Actual behaviour
The iterator seems to stop at the first invalid frame

## Reproduction steps
Sample repo at https://github.com/woelper/img_gif_test

Image is from linked issue https://github.com/woelper/oculante/issues/60

```
use image;
use image::codecs::gif::GifDecoder;
use image::AnimationDecoder;
use reqwest;

const URL: &str = "https://user-images.githubusercontent.com/3613791/198876501-61f76e9c-ef0f-46fa-8e4b-a5e5b20fcecf.gif";

fn main() {
    let img_bytes = reqwest::blocking::get(URL).unwrap().bytes().unwrap();
    let cursor = std::io::Cursor::new(img_bytes);
    let gif_decoder = GifDecoder::new(cursor).unwrap();

    // will fail because of "unknown block type encountered"
    // let frames = gif_decoder.into_frames().collect_frames().unwrap();

    for f in gif_decoder.into_frames() {
        match f {
            Ok(_) => println!("Frame decoded OK"),
            Err(e) => println!("{e}"),
        }
        // program will hang here forever
    }
}

```

**Comment by fintelia** [comment]
Did some investigation. There's actually two bugs here:
1. gif hangs if you ask for a new frame after receiving an error querying the previous one.
2. gif's frame iterator repeatedly calls into the underlying decoder when it encounters an error. So even if (1) was fixed, there'd still be an infinite loop.

@lowkin18 the difference is the `collect_frames` which stops querying for future frames after getting the first error. Basically the same as breaking out of the loop on error.

**Comment by kornelski** [comment]
This works correctly now
