### ISSUE TITLE
Error in decoder when code size of 1 is used

### ISSUE THREAD

**Issue by nwin** [image-rs/image-gif#20]
While fixing #16 also fixes #19 it is unclear to me why that is so.

**Comment by HeroicKatora** [comment]
I'm decently sure that a code size of `1` is invalid. That is currently enforced and corrected so this shouldn't occur in practice. Furthermore, the [specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt) suggests that an error is correct.

> Because of some algorithmic constraints however, black & white images which have one color bit must be
indicated as having a code size of 2.
