### ISSUE TITLE
Parallel encoding?

### ISSUE THREAD

**Issue by kornelski** [image-rs/image-gif#42]
I'd like to speed up encoding by encoding frames in parallel. Is that a case you'd like to support?

I see a couple ways to do it:

1. built in into the gif encoder: a method such as `write_frame_async()` could take the image data and perform encoding in a thread (handling queueing/writing in to file in the right order internally).

2. separate `encode_frame()` that performs LZW (so the caller can arrange encoding of frames in parallel), and a quick sync `write_encoded_frame()` that just writes out the encoded data.

```rust
let frames = images.par_iter().map(convert).map(encode_frame).collect();
for f in farmes {
    encoder.write_encoded_frame(f);
}
```

**Comment by pornel** [comment]
For now Amdahl's law has won, and just running encoder on its own thread is fast enough.

**Comment by kornelski** [comment]
I've optimized the rest of my process to the point LZW is the bottleneck, so reopening :)
