### ISSUE TITLE
how to use Encoder to write background ?

### ISSUE THREAD

**Issue by hawkingrei** [image-rs/image-gif#47]
when I resize the image and write the resized frame into encoder. I find the problem that it can write rightly transparent color. the encoder cannot write background color to gif.

my code is [here](https://github.com/hawkingrei/learning-rust/tree/feat/new_gif_resize/gif-resize)
you can run it by  `cargo run --release test.gif`

why has this picture green noise？

**Comment by ArturKovacs** [comment]
The provided link is broken. Is the question still relevant? Otherwise I'll close this.
