### ISSUE TITLE
Support gifs with more than 256 colors

### ISSUE THREAD

**Issue by sunjay** [image-rs/image-gif#48]
[Apparently, it is possible (with some extra work) to create a gif with more than 256 colors.](https://webmasters.stackexchange.com/questions/304/can-i-have-an-animated-gif-with-more-than-256-colours-per-frame) It would be great if this crate could provide a way to do that, even if it was a higher level interface over Encoder.

**Comment by Shnatsel** [comment]
The tool referenced in the stackoverflow answer is already written in Rust. See https://crates.io/crates/gifski

It also exposes Rust APIs. So what you're requesting already exists, and in fact uses this crate as a backend.
