### ISSUE TITLE
cargo test fails with archive from crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [image-rs/image-gif#51]
```rust
---- src/lib.rs -  (line 38) stdout ----
thread 'src/lib.rs -  (line 38)' panicked at 'test executable failed:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

', src/librustdoc/test.rs:356:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- src/lib.rs -  (line 18) stdout ----
thread 'src/lib.rs -  (line 18)' panicked at 'test executable failed:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

', src/librustdoc/test.rs:356:17
```

I'm packaging `gif` and we always run `cargo test` to ensure that library works fine in distribution. But unfortunately `gif` one fails (I assume because you exclude test data). Could you either include it or make it to not fail in case data is missing? Thanks.

**Comment by HeroicKatora** [comment]
This reminded me, I've just opened a PR on [image](https://github.com/image-rs/image/pull/1557) that could ensure that tests can be ran with the archives from crates. You might want to have a look, and I'll see when I get around to porting it to `gif` for additional data points of usage.

**Comment by kornelski** [comment]
Maybe do the opposite, and remove tests from the release tarball? 

Cargo doesn't support testing of packaged crates nor crates.io dependencies. IMHO the published tarballs are not meant to run tests, and stripping tests will save majority of users a bit of bandwidth and storage.

**Comment by kornelski** [comment]
I've moved some tests out, but that wasn't sufficient. There are still tests inline in .rs files that are published, so this is WONTFIX.
