### ISSUE TITLE
Mysterious background color

### ISSUE THREAD

**Issue by kornelski** [image-rs/image-gif#52]
In this file:

![m4nb](https://user-images.githubusercontent.com/72159/54464776-fe020d00-476f-11e9-930c-cbb70ad75afc.gif)

(from http://www.theimage.com/animation/pages/disposal2.html)

2nd frame and later have `DisposalMethod::Background` with `frame.transparent` == 255, and `bg_color` = 0. Actual paletted colors are also different.

And yet, all image viewers that I can find agree that these frames have a transparent background.

How's that possible? Could it be a parsing bug in this library?

**Comment by yvt** [comment]
It seems that none of web browsers actually use the background color:

- <https://hg.mozilla.org/mozilla-central/file/tip/image/decoders/nsGIFDecoder2.cpp#l585>
- <https://github.com/google/skia/blob/fe19203eb7d7e8bef528287494d82c2eb4efff0e/third_party/gif/SkGifImageReader.cpp#L518-L540>
