### ISSUE TITLE
SetParameter trait implementation is too broad

### ISSUE THREAD

**Issue by fintelia** [image-rs/image-gif#60]
This crate has a blanket implementation for SetParameter:
```rust
impl<T> SetParameter for T {}
```
This causes the trait to be implemented not just for every type in this library, but for every (Sized) type in existence. Any library that depends on this crate will thus have its documentation cluttered with implementations of this trait. It would be better to restrict the implementation to only types that are meant to deal with parameters

**Comment by HeroicKatora** [comment]
Also see the critique of the pattern overall:
https://github.com/image-rs/image-png/issues/139
