### ISSUE TITLE
DGifGetLine() in C API may cause undefined behavior

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-gif#62]
`util::copy_memory` panics if source buffer is larger than destination:

https://github.com/image-rs/image-gif/blob/8318addc1f48ba7c92392fc5a4e4e42f2f167703/src/util.rs#L8-L10

`DGifGetLine()` calls it with user-supplied `dst` length that may be lower than `src` length, see lines 295 and 298:

https://github.com/image-rs/image-gif/blob/8318addc1f48ba7c92392fc5a4e4e42f2f167703/src/c_api.rs#L291-L300

This may cause the `util::copy_memory` call to panic and trigger unwinding. Since there is no panic handling in `DGifGetLine()` it will unwind across the FFI boundary, which is undefined behavior.

**Comment by HeroicKatora** [comment]
Hm, reopened this by error. The thought process was that purely changing the utils to the intrinsic doesn't make the check more lenient and should panic *more often*. But both buffers involved have a length of exactly `cmp::min(buffer.len(), len as usize)`. Well, another look didn't really hurt at least I can get back to that in my eventual `crev` review.
